### ISSUE TITLE
大佬这个要怎么配置才能使用呢

### ISSUE THREAD

**Issue by KDWangBoss** [zydemail/componentPlaceholder#1]

**Comment by zydemail** [comment]
ts版本这样用：
`
@Component({
  componentPlaceholder: {
    'xTest': 'view',
    'list': 'view',  // 新增组件需要写在这里，不配置开发者工具会报错
    'tab-bar': 'view'// 新增组件需要写在这里
  }
})
`
js版本
`
  componentPlaceholder: {
    'xTest': 'view',
    'hello': 'view',
    'tabBar': 'view'
  },
`

**Comment by KDWangBoss** [comment]
好的，谢谢啦
